//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SWZ_Petrol_Station
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLIENTS
    {
        public CLIENTS()
        {
            this.TRANSACTIONS = new HashSet<TRANSACTIONS>();
            this.RESERVATIONS = new HashSet<RESERVATIONS>();
        }
    
        public int CLI_PKid { get; set; }
        public string CLI_LOGIN { get; set; }
        public string CLI_PASSWORD { get; set; }
        public int CLI_ACCTYPE { get; set; }
        public Nullable<int> CLI_PAOUMT { get; set; }
        public Nullable<System.DateTime> CLI_LASTCHANGE { get; set; }
        public Nullable<int> COM_PKid { get; set; }
        public Nullable<int> PRS_PKid { get; set; }
    
        public virtual ICollection<TRANSACTIONS> TRANSACTIONS { get; set; }
        public virtual COMPANY COMPANY { get; set; }
        public virtual PERSON PERSON { get; set; }
        public virtual ICollection<RESERVATIONS> RESERVATIONS { get; set; }
    }
}
