//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SWZ_Petrol_Station
{
    using System;
    using System.Collections.Generic;
    
    public partial class COMPANY
    {
        public COMPANY()
        {
            this.CLIENTS = new HashSet<CLIENTS>();
        }
    
        public int COM_PKid { get; set; }
        public string COM_NAME { get; set; }
        public long COM_NIP { get; set; }
        public long COM_REGON { get; set; }
        public Nullable<int> PLA_PKid { get; set; }
    
        public virtual ICollection<CLIENTS> CLIENTS { get; set; }
        public virtual PLACES PLACES { get; set; }
    }
}
