//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SWZ_Petrol_Station
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPLOYEES
    {
        public int EMP_PKid { get; set; }
        public string EMP_JOB { get; set; }
        public int EMP_PERMISSIONS { get; set; }
        public string EMP_IDNO { get; set; }
        public string EMP_PASSWORD { get; set; }
        public int PRS_PKid { get; set; }
    
        public virtual PERSON PERSON { get; set; }
    }
}
