//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SWZ_Petrol_Station
{
    using System;
    using System.Collections.Generic;
    
    public partial class FUEL_TANK
    {
        public int FUE_PKid { get; set; }
        public int FUE_NUMBER { get; set; }
        public System.DateTime FUE_DATE { get; set; }
        public double FUE__PRESSURE { get; set; }
        public double FUE_TEMPERATURE { get; set; }
        public Nullable<double> FUE_AMOUNT { get; set; }
    }
}
