//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SWZ_Petrol_Station
{
    using System;
    using System.Collections.Generic;
    
    public partial class MONITORING_VIDEO
    {
        public int MOV_PKid { get; set; }
        public string MOV_PATH { get; set; }
        public System.DateTime MOV_DATE { get; set; }
        public string MOV_CAMERANO { get; set; }
        public double MOV_FILESIZE { get; set; }
    }
}
