//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SWZ_Petrol_Station
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERFORMANCE_MONITORING
    {
        public int PER_PKid { get; set; }
        public string PER_NAME { get; set; }
        public double PER_VALUE { get; set; }
        public System.DateTime PER_DATE { get; set; }
        public string PER_SENSORNO { get; set; }
        public int POS_PKid { get; set; }
    
        public virtual POSITION_SERVICE POSITION_SERVICE { get; set; }
    }
}
