//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SWZ_Petrol_Station
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERSON
    {
        public PERSON()
        {
            this.CLIENTS = new HashSet<CLIENTS>();
            this.EMPLOYEES = new HashSet<EMPLOYEES>();
        }
    
        public int PRS_PKid { get; set; }
        public string PRS_NAME { get; set; }
        public string PRS_MIDNAME { get; set; }
        public string PRS_SURNAME { get; set; }
        public long PRS_PESEL { get; set; }
        public Nullable<long> PRS_NIP { get; set; }
        public System.DateTime PRS_BIRTHDATE { get; set; }
        public int PLA_PKid { get; set; }
    
        public virtual ICollection<CLIENTS> CLIENTS { get; set; }
        public virtual ICollection<EMPLOYEES> EMPLOYEES { get; set; }
        public virtual PLACES PLACES { get; set; }
    }
}
