//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SWZ_Petrol_Station
{
    using System;
    using System.Collections.Generic;
    
    public partial class PLACES
    {
        public PLACES()
        {
            this.COMPANY = new HashSet<COMPANY>();
            this.PERSON = new HashSet<PERSON>();
        }
    
        public int PLA_PKid { get; set; }
        public string PLA_CITY { get; set; }
        public string PLA_POSTCODE { get; set; }
        public int PLA_STREET { get; set; }
        public string PLA_HOUSENO { get; set; }
        public Nullable<int> PLA_BUILDNAME { get; set; }
        public string PLA_COUNTRY { get; set; }
    
        public virtual ICollection<COMPANY> COMPANY { get; set; }
        public virtual ICollection<PERSON> PERSON { get; set; }
    }
}
