//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SWZ_Petrol_Station
{
    using System;
    using System.Collections.Generic;
    
    public partial class POSITION_SERVICE
    {
        public POSITION_SERVICE()
        {
            this.PERFORMANCE_MONITORING = new HashSet<PERFORMANCE_MONITORING>();
            this.SERVICES_POSITION = new HashSet<SERVICES_POSITION>();
            this.POSITION_TRANSACTIONS_LIST = new HashSet<POSITION_TRANSACTIONS_LIST>();
            this.RESERVATIONS = new HashSet<RESERVATIONS>();
        }
    
        public int POS_PKid { get; set; }
        public string POS_NAME { get; set; }
        public string POS_TYPE { get; set; }
        public string POS_CAPACITY_UNIT { get; set; }
        public double POS_CAPACITY { get; set; }
    
        public virtual ICollection<PERFORMANCE_MONITORING> PERFORMANCE_MONITORING { get; set; }
        public virtual ICollection<SERVICES_POSITION> SERVICES_POSITION { get; set; }
        public virtual ICollection<POSITION_TRANSACTIONS_LIST> POSITION_TRANSACTIONS_LIST { get; set; }
        public virtual ICollection<RESERVATIONS> RESERVATIONS { get; set; }
    }
}
