//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SWZ_Petrol_Station
{
    using System;
    using System.Collections.Generic;
    
    public partial class POSITION_TRANSACTIONS_LIST
    {
        public int PTL_PKID { get; set; }
        public int POS_PKid { get; set; }
        public int TRA_PKid { get; set; }
    
        public virtual POSITION_SERVICE POSITION_SERVICE { get; set; }
        public virtual TRANSACTIONS TRANSACTIONS { get; set; }
    }
}
