//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SWZ_Petrol_Station
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRICELIST
    {
        public PRICELIST()
        {
            this.TRANSACTIONS = new HashSet<TRANSACTIONS>();
        }
    
        public int PRL_PKid { get; set; }
        public string PRL_UNIT { get; set; }
        public double PRL_PRICE { get; set; }
        public int PRL_LOYALTY_POINTS_AMOUNT { get; set; }
        public int SER_PKid { get; set; }
    
        public virtual ICollection<TRANSACTIONS> TRANSACTIONS { get; set; }
        public virtual SERVICE SERVICE { get; set; }
    }
}
