//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SWZ_Petrol_Station
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRIZES
    {
        public int PRI_PKid { get; set; }
        public string PRI_NAME { get; set; }
        public Nullable<double> PRI_NUMBER_OF_POINTS { get; set; }
    }
}
