//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SWZ_Petrol_Station
{
    using System;
    using System.Collections.Generic;
    
    public partial class RESERVATIONS
    {
        public int RES_PKid { get; set; }
        public System.DateTime RES_RESERVATION_DATE { get; set; }
        public System.DateTime RES_DATE_TERM { get; set; }
        public int POS_PKid { get; set; }
        public int CLI_PKid { get; set; }
    
        public virtual CLIENTS CLIENTS { get; set; }
        public virtual POSITION_SERVICE POSITION_SERVICE { get; set; }
    }
}
