//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SWZ_Petrol_Station
{
    using System;
    using System.Collections.Generic;
    
    public partial class SERVICE
    {
        public SERVICE()
        {
            this.PRICELIST = new HashSet<PRICELIST>();
            this.SERVICES_POSITION = new HashSet<SERVICES_POSITION>();
        }
    
        public int SER_PKid { get; set; }
        public string SER_NAME { get; set; }
    
        public virtual ICollection<PRICELIST> PRICELIST { get; set; }
        public virtual ICollection<SERVICES_POSITION> SERVICES_POSITION { get; set; }
    }
}
