//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SWZ_Petrol_Station
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DB_9D7C73_karolwieczorek9Entities1 : DbContext
    {
        public DB_9D7C73_karolwieczorek9Entities1()
            : base("name=DB_9D7C73_karolwieczorek9Entities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CLIENTS> CLIENTS { get; set; }
        public virtual DbSet<COMPANY> COMPANY { get; set; }
        public virtual DbSet<EMPLOYEES> EMPLOYEES { get; set; }
        public virtual DbSet<MONITORING_VIDEO> MONITORING_VIDEO { get; set; }
        public virtual DbSet<PERFORMANCE_MONITORING> PERFORMANCE_MONITORING { get; set; }
        public virtual DbSet<PERSON> PERSON { get; set; }
        public virtual DbSet<PLACES> PLACES { get; set; }
        public virtual DbSet<POSITION_SERVICE> POSITION_SERVICE { get; set; }
        public virtual DbSet<POSITION_TRANSACTIONS_LIST> POSITION_TRANSACTIONS_LIST { get; set; }
        public virtual DbSet<PRICELIST> PRICELIST { get; set; }
        public virtual DbSet<PRIZES> PRIZES { get; set; }
        public virtual DbSet<RESERVATIONS> RESERVATIONS { get; set; }
        public virtual DbSet<SERVICE> SERVICE { get; set; }
        public virtual DbSet<SERVICES_POSITION> SERVICES_POSITION { get; set; }
        public virtual DbSet<TRANSACTIONS> TRANSACTIONS { get; set; }
    }
}
