//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SWZ_Petrol_Station
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRANSACTIONS
    {
        public TRANSACTIONS()
        {
            this.POSITION_TRANSACTIONS_LIST = new HashSet<POSITION_TRANSACTIONS_LIST>();
        }
    
        public int TRA_PKid { get; set; }
        public string TRA_NAME { get; set; }
        public System.DateTime TRA_DATE { get; set; }
        public bool TRA_INVOICED { get; set; }
        public Nullable<int> TRA_AMOUNT { get; set; }
        public string TRA_ALL { get; set; }
        public Nullable<int> PRL_PKid { get; set; }
        public Nullable<int> CLI_PKid { get; set; }
    
        public virtual CLIENTS CLIENTS { get; set; }
        public virtual ICollection<POSITION_TRANSACTIONS_LIST> POSITION_TRANSACTIONS_LIST { get; set; }
        public virtual PRICELIST PRICELIST { get; set; }
    }
}
